flask_apidoc/__init__.py
from flask import request, Blueprint, Flask
from flask_apidoc import views
from types import MethodType
from functools import wraps, update_wrapper
from collections import OrderedDict
import yaml

_api_list = OrderedDict()


def fire_event_bp(func, apidoc):
    """ 蓝图装饰器, 装饰实例方法"""
    @wraps(func)
    def wrapper(app, *args, **kw):
        ret = func(*args, **kw)
        apidoc.show_functions(app)
        return ret
    return wrapper


class _Api(object):

    def __init__(self, url, endpoint, methods, func):
        self.url = url
        self.endpoint = endpoint
        self.func = func
        if methods:
            self._methods = [method.upper() for method in methods]
        else:
            self._methods = []
        self.parser = _DOCParser(self)
    
    def method_doc(self, method):
        return self.parser.handle(method)
    
    def _doc(self):
        return self.func.__doc__

    @property
    def hash_key(self):
        return hash(self.endpoint)
    
    @property
    def methods(self):
        methods = []
        _methods = ['GET', 'POST', 'PUT', 'DELETE']
        for method in _methods:
            if method in self._methods:
                methods.append(method)
        return methods

    def __hash__(self):
        return self.hash_key

    def __eq__(self, other):
        if not getattr(other, 'hash_key'):
            return False
        return self.hash_key == other.hash_key

    def __repr__(self):
        return '<Api url: {}, endpoint: {}>'.format(self.url, self.endpoint)


class _DOCParser(object):

    def __init__(self, api):
        self.api = api

    def handle(self, method):
        try:
            docs = yaml.load(self.api._doc())
            self.docs = self._key_upper(docs) or {}
        except Exception as e:
            self.docs = {'desc': self.api._doc()}
        return self.info(method)
    
    def _key_upper(self, docs):
        return {k.upper(): v for k, v in docs.items()}
    
    def _method_info(self, method):
        """ 文档信息"""
        method_info = self.docs.get(method, {})
        return method_info
    
    def info(self, method):
        info = self._method_info(method)
        return info

class APIDoc(object):

    def __init__(self, app=None):
        self.load_endpoints = set()
        self.view_functions = {}
        self._hidden_bp_list = ['apidocs']
        self._hidden_endpoints = []

        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        app.config.setdefault('APIDOC_URL', '/apidocs')
        app.config.setdefault('APIDOC_BLUEPRINT_NAME', 'apidocs')

        if not hasattr(app, 'extensions'):
            app.extensions = {}

        self.app = app
        app.extensions['api_doc'] = self
        if app.config['DEBUG']:
            """ 动态的给app register_blueprint加上装饰器"""
            rb = fire_event_bp(self.app.register_blueprint, self)
            self.app.register_blueprint = MethodType(rb, self.app)
            self.configure_blueprint(app)
            self.show_functions(app)

    def configure_blueprint(self, app):
        from flask_apidoc import views
        app.register_blueprint(views.bp)
    
    def hidden_blueprint(self, bp):
        """ 忽略的blueprint"""
        self._hidden_bp_list.add(bp)
    
    def is_hidden_endpoint(self, endpoint):
        """ 过滤endpoint"""
        bp_name = endpoint.split('.')[0]
        if bp_name in self._hidden_bp_list:
            return True
        else:
            return False
    
    def show_functions(self, app):
        """ 显示的函数"""
        view_functions = app.view_functions
        for endpoint, func in view_functions.items():
            if 'static' in endpoint:
                continue
            if endpoint in self.load_endpoints:
                continue

            self.view_functions[endpoint] = func
        self.parse_app_rules()
    
    def is_first_rule(self, rule):
        """ 第一次加载规则"""
        endpoint = rule.endpoint
        result = (
            endpoint in self.view_functions and
            endpoint not in self.load_endpoints and
            not self.is_hidden_endpoint(endpoint)
        )
        return result
    
    def parse_app_rules(self):
        """ 解析所有规则"""
        global _api_list
        rules = self.app.url_map._rules
        for rule in rules:
            endpoint = rule.endpoint
            if self.is_first_rule(rule):
                func = self.view_functions[endpoint]
                self.load_endpoints.add(endpoint)
                api = _Api(rule.rule, endpoint, rule.methods, func)
                _api_list[endpoint] = api

flask_apidoc/views.py
from flask import Blueprint, render_template, current_app
from flask_apidoc.utils import templates_path, static_path
import flask_apidoc

bp = Blueprint(
    'apidocs',
    __name__,
    url_prefix='/apidocs',
    template_folder=templates_path,
    static_folder=static_path,
)


@bp.route('/')
def index():
    api_list = flask_apidoc._api_list
    return render_template('index.html', api_list=api_list)


@bp.route('/<_endpoint>/<method>')
def endpoint(_endpoint, method):
    api = flask_apidoc._api_list.get(_endpoint)
    docs = api.parser.handle(method)
    return render_template('endpoint.html', api=api, docs=docs)

flask_apidoc/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
    <link rel="stylesheet" href="/apidocs/static/css/app.css">
    <title>{% block title %}Api 接口列表{% endblock %}</title>
</head>

<body>
    {% include "header.html" %}
    {% block content %}{% endblock %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="/apidocs/static/js/app.js"></script>
    <script>
        hljs.initHighlightingOnLoad();
    </script>
    {% block load_js %}{% endblock %}
</body>

</html>

flask_apidoc/templates/endpoint.html
{% extends "base.html" %}
{% from "func.html" import render_params, render_mock_form %}
{% block content %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h4>路由</h4>
                <pre><code class="bash">{{ api.url }}</code></pre>
                <h4>接口描述</h4>
                <pre><code>{{ docs.desc or "" }}</code></pre>
                <h4>参数</h4>
                {{ render_params(docs.param) }}
                <h4>返回值</h4>
                <pre><code class="json">{{ docs.resp or "" }}</code></pre>

            </div>
            {{ render_mock_form(api, docs) }}
        </div>
    </div>
</div>
{% endblock %}

{% block load_js %}
<script>
    $('.mock').click(function(){
        $('.mock-form').show();
    })
</script>
{% endblock %}

flask_apidoc/templates/func.html
{% macro render_method(endpoint, method) %}
{# 渲染方法　#}
{% set method_colors = {
    'GET': '#61affe',
    'POST': '#49cc90',
    'PUT': '#fca130',
    'DELETE': '#f93e3e',
}%}
<a
    class="btn btn-default btn-sm"
    style="width: 80px; background-color: {{ method_colors[method]}}; color: #fff; font-weight: 700;"
    href="{{ url_for('apidocs.endpoint', _endpoint=endpoint, method=method) }}"
>{{ method }}</a>
{% endmacro %}


{% macro render_params(params) %}
{# 渲染文档参数　#}
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 20%">字段</th>
            <th style="width: 10%">类型</th>
            <th style="width: 10%">必填</th>
            <th style="width: 20%">默认值</th>
            <th style="width: 40%">描述</th>
        </tr>
    </thead>
    <tbody>
        {% if params %}
            {% for field, options in params.items() %}
            <tr>
                <td>{{ field }}</td>
                <td>{{ options['type'] or 'string' }}</td>
                <td>{{ options['required'] or 'False' }}</td>
                <td>{{ options['default'] or '' }}</td>
                <td>{{ options['desc'] or '' }}</td>
            </tr>
            {% endfor %}
        {% endif %}
    </tbody>
</table>
{% endmacro %}

{% macro render_mock_form(api, docs) %}
{# 渲染模拟请求 #}
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">API请求</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
            ...
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info">提交</button>
            <button type="button" class="btn btn-warning">重置</button>
        </div>
        </div>
    </div>
</div>
{% endmacro %}

flask_apidoc/templates/header.html
<header class="navbar navbar-static-top bs-docs-nav bg-header">
    <div class="container">
        <div class="navbar-header">
            <a href="/apidocs">
                <b>API 接口文档</b>
            </a>
        </div>
        {% if docs is defined %}
        <ul class="nav navbar-nav">
            <li>
                <a href="javascript: void(0);" data-toggle="modal" data-target="#myModal"><b>API请求</b></a>
            </li>
        </ul>
        {% endif %}
    </div>
</header>

flask_apidoc/templates/index.html
{% extends "base.html" %}

{% from 'func.html' import render_method with context %}

{% block content %}
<div class="container" style="margin-top: 100px;">
    <div class="list-group" style="width: 100%;">
        {% for api in api_list.values() %}
        <div class="list-group-item">
            <span class="item" style="color: #2f6f9f; font-size: 16px; line-height: 31px;">
                {{ api.url }}
            </span>
            <div style="float: right">
                {% for method in api.methods %}
                    {{ render_method(api.endpoint, method) }}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block load_js %}
{% endblock %}